version: "3.1"

services:
  servernode:
    build:
      context: .
      dockerfile: dockerfile.node
    image: servernode
    ports:
      - 4200:4200
    volumes:
      - "/webapps/node_modules"
      - "./:/webapps"
    deploy:
      resources:
        limits:
          memory: 6048M